# -*- coding: utf-8 -*-
"""translator try.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zV7EsVF-3PeqeXoVhW1CcyolbaR7Q_Lw
"""

!pip install englisttohindi
!pip install translate

from englisttohindi.englisttohindi import EngtoHindi
from translate import Translator

def translate_text(input_text, translation_option):
    try:
        if translation_option == "Hindi":
            trans = EngtoHindi(input_text)
            output_text = trans.convert
        elif translation_option == "French":
            translator = Translator(to_lang="fr")
            output_text = translator.translate(input_text)
        else:
            output_text = "Invalid selection"
    except Exception as e:
        output_text = f"Error: {str(e)}"
    return output_text

input_text = "This is a test."

# Test translation to Hindi
translation_option = "Hindi"
hindi_translation = translate_text(input_text, translation_option)
print(f"Translation to Hindi: {hindi_translation}")

# Test translation to French
translation_option = "French"
french_translation = translate_text(input_text, translation_option)
print(f"Translation to French: {french_translation}")